# Generated by Django 6.0.1 on 2026-02-02 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Participant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('name', models.CharField(blank=True, max_length=200, null=True)),
                ('position', models.CharField(choices=[('participant', 'Participant'), ('top10', 'Top 10'), ('top3', 'Top 3 Winner')], default='participant', max_length=20)),
                ('certificate_generated', models.BooleanField(default=False)),
            ],
        ),
    ]
